on:
  push:
    branches: 
      - master
      
jobs:
  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: copy build/ directory
        uses: burnett01/rsync-deployments@5.2.1
        with:
        switches: -avzr --delete
          path: src/build/
          remote_path: /var/www/mirabilis-server/
          remote_host: '51.250.10.120'
          remote_user: physphile
