on:
  push:
    branches: 
      - master
      
jobs:
  deploy:
    name: deploy to server
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          rsync physphile@51.250.10.120
          cd /var/www/mirabilis-server
          sudo git pull
          nvm use
          npm i
          npm start
